Implement position and monster moving
utilForever/CubbyTower pull request #17
Opened 2021-07-10 09:51 UTC by IHIHHIHI

This revision includes:

- Add "position" struct
- Add "distance" struct
- Add monster path handing

2021-07-10 13:25 UTC, utilForever requested changes
You should check my feedback.
Also, I suggest change the file name 'Path.hpp/cpp' to 'PathSystem.hpp/cpp' and 'PathTests.cpp' to 'PathSystemTests.cpp'.

2021-07-10 13:25 UTC, utilForever commented on Includes/CubbyTower/Components/Distance.hpp
> +    double s;
```suggestion
    double distance;
```

2021-07-10 13:25 UTC, utilForever commented on Includes/CubbyTower/Systems/Path.hpp
> +
Delete a blank line.

2021-07-10 13:25 UTC, utilForever commented on Includes/CubbyTower/Systems/Path.hpp
> +//! This function called every frame and gives enemies' position using distance
```suggestion
//! This function called every frame and gives the position of enemies using distance.
```

2021-07-10 13:25 UTC, utilForever commented on Includes/CubbyTower/Systems/Path.hpp
> +void Path(entt::registry& registry);
```suggestion
void UpdatePathSystem(entt::registry& registry);
```

2021-07-10 13:25 UTC, utilForever commented on Sources/CubbyTower/Systems/Path.cpp
> +void Path(entt::registry& registry)
```suggestion
void UpdatePathSystem(entt::registry& registry)
```

2021-07-10 13:25 UTC, utilForever commented on Sources/CubbyTower/Systems/Path.cpp
> +    auto view = registry.view<Distance,Position>();
```suggestion
    auto view = registry.view<Distance, Position>(); 
```

2021-07-10 13:25 UTC, utilForever commented on Sources/CubbyTower/Systems/Path.cpp
> +        auto &dis = view.get<Distance>(enemy);
```suggestion
        auto& pos = view.get<Position>(enemy);
        auto& dist = view.get<Distance>(enemy);
```

2021-07-10 13:25 UTC, utilForever commented on Sources/CubbyTower/Systems/Path.cpp
> +        pos.x = dis.s;
```suggestion
        pos.x = dist.distance;
```

2021-07-10 13:25 UTC, utilForever commented on Includes/CubbyTower/Systems/Path.hpp
> +namespace CubbyTower
```suggestion
namespace CubbyTower::Path
```

2021-07-10 13:25 UTC, utilForever commented on Sources/CubbyTower/Systems/Path.cpp
> +namespace CubbyTower
```suggestion
namespace CubbyTower::Path
```

2021-07-10 13:25 UTC, utilForever commented on Tests/UnitTests/Systems/PathTests.cpp
> +    Path(registry);
```suggestion
    Path::UpdatePathSystem(registry);
```

2021-07-10 13:25 UTC, utilForever commented on Tests/UnitTests/Systems/PathTests.cpp
> +    registry.emplace<Distance>(enemy1 , 5.0);
```suggestion
    registry.emplace<Position>(enemy1, 0.0, 0.0);
    registry.emplace<Distance>(enemy1, 5.0);
```

2021-07-10 13:25 UTC, utilForever commented on Tests/UnitTests/Systems/PathTests.cpp
> +    for (auto [enemy, pos] : registry.view<Tag::Enemy , Position>().each())
```suggestion
    for (auto [enemy, pos] : registry.view<Tag::Enemy, Position>().each())
```

2021-07-10 13:25 UTC, utilForever commented on Tests/UnitTests/Systems/PathTests.cpp
> +
Delet these lines.

2021-07-10 13:25 UTC, utilForever commented on Tests/UnitTests/Systems/PathTests.cpp
> +TEST_CASE("[Path] - Path")
```suggestion
TEST_CASE("[PathSystem] - UpdatePathSystem")
```

2021-07-10 13:25 UTC, utilForever commented on Tests/UnitTests/Systems/PathTests.cpp
> +#include <CubbyTower/Systems/Path.hpp>
```suggestion
#include <CubbyTower/Systems/PathSystem.hpp>
```

2021-07-10 13:25 UTC, utilForever commented on Sources/CubbyTower/Systems/Path.cpp
> +#include <CubbyTower/Systems/Path.hpp>
```suggestion
#include <CubbyTower/Systems/PathSystem.hpp>
```

2021-07-10 13:26 UTC, IHIHHIHI commented on Includes/CubbyTower/Systems/Path.hpp
> +
14 번 줄 메모

2021-07-10 14:09 UTC, utilForever approved these changes
LGTM now. Thanks for your work! 🎉

2021-07-11 01:25 UTC, red1108 approved these changes
LGTM.
I wonder why you add ::Path

2021-07-11 01:42 UTC, utilForever commented
@red1108 To improve readability for code. 👓

2021-07-11 01:42 UTC, merged