feat: Add distance-based attack system
utilForever/CubbyTower pull request #19
Opened 2021-07-11 10:12 UTC by red1108

The following items have been implemented.

- Add `AttackRange` component
- Add `HealthPoint` component
- Add `TargetPriority` component
- Refactor `TargetMask` component code
- Refactor `TypeMask` component code
- Add position parameter to `BuyArrowTower` and add update new components
- Add distance-based attack system to `Attack` function
- Add new testing system

2021-07-12 19:04 UTC, IHIHHIHI commented on Includes/CubbyTower/Components/AttackRange.hpp
> +    double attackRange;
이건 민규가 아니라 찬호님에게 여쭤보고 싶은 것인데, 변수명 대소문자에 관한 규칙은 어떻게 되나요?

2021-07-12 19:07 UTC, IHIHHIHI requested changes

2021-07-12 19:07 UTC, IHIHHIHI commented on Includes/CubbyTower/Helpers/TowerHelpers.hpp
> +void BuyArrowTower(entt::registry& registry, double x, double y);
position struct를 받는 오버로딩 되는 함수 하나를 더 정의하는건 어떤지?

2021-07-12 19:08 UTC, IHIHHIHI approved these changes

2021-07-12 19:08 UTC, IHIHHIHI commented on Includes/CubbyTower/Helpers/TowerHelpers.hpp
> +void BuyArrowTower(entt::registry& registry, double x, double y);
다시 생각해보니 반드시 필요한건 아닐지도

2021-07-13 03:30 UTC, red1108 commented on Includes/CubbyTower/Helpers/TowerHelpers.hpp
> +void BuyArrowTower(entt::registry& registry, double x, double y);
Position struct로 인자 넣을까 생각해봤는데 딱히 넣을이유도 없고 안넣을이유도 안보여서 그냥 간단하게 double x, double y로 함

2021-07-13 03:45 UTC, IHIHHIHI commented on Includes/CubbyTower/Helpers/TowerHelpers.hpp
> +void BuyArrowTower(entt::registry& registry, double x, double y);
추가할 이유가 없진 않지 않아? 이번 PR에선 아니더라도 하나 만들어두면 좋을듯

2021-07-13 06:34 UTC, red1108 commented on Includes/CubbyTower/Helpers/TowerHelpers.hpp
> +void BuyArrowTower(entt::registry& registry, double x, double y);
나중에 gui할때쯤 실제로 저 함수 쓸때 되면 그때 상황보고 바꿀생각임

2021-07-15 14:15 UTC, utilForever requested changes
You should change some code. Please check them. 🌡️

2021-07-15 14:15 UTC, utilForever commented on Includes/CubbyTower/Components/AttackRange.hpp
> +    double attackRange;
변수명은 소문자로 시작하되 단어와 단어를 붙일 경우 두번째부터 대문자를 사용합니다.
예를 들어, `number` 그리고 `totalNumber`가 있겠네요.

2021-07-15 14:15 UTC, utilForever commented on Includes/CubbyTower/Components/HealthPoint.hpp
> +#endif  // CUBBYTOWER_HEALTH_POINT_HPP
```suggestion
#ifndef CUBBYTOWER_HEALTH_HPP
#define CUBBYTOWER_HEALTH_HPP

namespace CubbyTower
{
//!
//! \brief Health struct.
//!
//! This struct stores the health of the entity.
//!
struct Health
{
    int health;
};
}  // namespace CubbyTower

#endif  // CUBBYTOWER_HEALTH_HPP
```

2021-07-15 14:15 UTC, utilForever commented on Includes/CubbyTower/Components/TargetPriority.hpp
> +    string priority = 2;
What is this? Why the type is `string`?

2021-07-15 14:15 UTC, utilForever commented on Sources/CubbyTower/Systems/AttackSystem.cpp
> +            const auto ePosition = registry.get<Position>(enemy);
```suggestion
            const auto towerPos = registry.get<Position>(tower);
            const auto enemyPos = registry.get<Position>(enemy);
```

2021-07-15 14:15 UTC, utilForever commented on Sources/CubbyTower/Systems/AttackSystem.cpp
> +            }
```suggestion
            if ((towerPos.x - enemyPos.x) * (towerPos.x - enemyPos.x) + (towerPos.y - enemyPos.y) * (towerPos.y - enemyPos.y) > attackRange * attackRange)
            {
                continue;
            }
```

2021-07-15 14:15 UTC, utilForever commented on Sources/CubbyTower/Systems/AttackSystem.cpp
> +            }
Also, you should apply coding style by `clang-format`.

2021-07-15 14:15 UTC, utilForever commented on Sources/CubbyTower/Systems/AttackSystem.cpp
> +                healthPoint.hp -= damage;
```suggestion
                // TODO: Consider the target priority, make a projectile
                // Simple attack test
                auto& health = registry.get<HealthPoint>(enemy);
                health.health -= damage;
```

2021-07-15 14:15 UTC, utilForever commented on Tests/UnitTests/Systems/AttackSystemTests.cpp
>      registry.emplace<TypeMask>(enemy1, 0b010); //type : ground
```suggestion
    registry.emplace<TypeMask>(enemy1, 0b010); // Type: ground
```

2021-07-15 14:15 UTC, utilForever commented on Tests/UnitTests/Systems/AttackSystemTests.cpp
>      registry.emplace<TypeMask>(enemy2, 0b011); //type : ground & stealth
```suggestion
    registry.emplace<TypeMask>(enemy2, 0b011); // Type: ground & stealth
```

2021-07-15 14:15 UTC, utilForever commented on Tests/UnitTests/Systems/AttackSystemTests.cpp
> +    registry.emplace<TypeMask>(enemy3, 0b010); //type : ground
```suggestion
    registry.emplace<TypeMask>(enemy3, 0b010); // Type: ground
```

2021-07-15 14:15 UTC, utilForever commented on Tests/UnitTests/Systems/AttackSystemTests.cpp
> +    for (auto [enemy, dist, hp, mask] : registry.view<Tag::Enemy, Distance, HealthPoint, TypeMask>().each())
You should apply coding style by `clang-format`.

2021-07-16 03:41 UTC, red1108 commented on Includes/CubbyTower/Components/TargetPriority.hpp
> +    string priority = 2;
OMG

2021-07-16 09:24 UTC, utilForever approved these changes
LGTM now. Thanks for your work! 🕊️

2021-07-16 09:25 UTC, merged