Monster
utilForever/CubbyTower pull request #31
Opened 2022-02-14 16:22 UTC by red1108

This revision includes:

    - Implement monster destroy event (When health is equal or less than  0)
        - Create struct 'Enemy'
            - This struct stores OnDestroy event
        - Add param OnDestroy to CreateMonster
        - Add DestroyMonster function
            - This is a basic function that just destroys an entity.
        - Update AttackSystem to destroy monster
        - Update AttackSystemTests to testing destroy monster

2022-02-14 16:27 UTC, red1108 commented
Enemy 랑 Monster 표현 둘중에 하나로 통일해야 될것 같습니다.

2022-02-14 16:43 UTC, IHIHHIHI commented on Includes/CubbyTower/Components/Enemy.hpp
> +struct Enemy
이거 이름을 Enemy로 하지 않아도 되지 않을까요?

2022-02-14 16:45 UTC, red1108 commented on Includes/CubbyTower/Components/Enemy.hpp
> +struct Enemy
일단 Tag이름이 Enemy라 Enemy라고 했습니다

2022-02-14 17:18 UTC, IHIHHIHI commented on Includes/CubbyTower/Components/Enemy.hpp
> +struct Enemy
Distance처럼 Enemy만 가질 수 있는 속성이어도 그 속성의 특징을 반영하게 이름을 짓는게 맞는 것 같습니다.

2022-02-15 14:14 UTC, utilForever requested changes
코드 전반적으로 수정이 필요할 거 같습니다.
우선 Enemy라는 Component는 필요하지 않습니다.
Enemy라는 Tag를 붙였으니 Enemy에게 필요한 Component들을 대입해주면 됩니다.
ECS 개념을 다시 한 번 생각해보기 바랍니다. 궁금한 점 있으면 채널에서 이야기하세요.

2022-02-17 00:47 UTC, utilForever commented
이 PR은 닫고 회의 시간 때 좀 더 자세히 설명하는 게 좋겠네요. 고생하셨습니다. 🙇

2022-02-17 00:47 UTC, closed without merging