Add Projectile
utilForever/CubbyTower pull request #35
Opened 2022-02-19 13:49 UTC by IHIHHIHI

- add component Velocity 
- add component Cooldown(not yet used)
- refactor function Attack
- add function CreateProjectile

TODO : 
- add tower components (projectile speed, effects of a projectile)
- add projectile components (lifetime, projectile effects ...etc)
- add functions(projectile rendering, collision handling,...)
- fix Attack function(add cooldown)

2022-02-20 02:23 UTC, red1108 approved these changes
LGTM

2022-02-21 15:11 UTC, utilForever requested changes
You should change some codes.

2022-02-21 15:11 UTC, utilForever commented on Includes/CubbyTower/Components/Velocity.hpp
> +    float vy;
```suggestion
    float dx;
    float dy;
```

2022-02-21 15:11 UTC, utilForever commented on Includes/CubbyTower/Components/Cooldown.hpp
> +    float nowTime;
```suggestion
    float totalTime;
    float leftTime;
```

2022-02-21 15:11 UTC, utilForever commented on Includes/CubbyTower/Components/Cooldown.hpp
> +//! This is used by the tower, or abilities(might be added later)
```suggestion
//! This is used by the tower, or abilities (might be added later).
```

2022-02-21 15:11 UTC, utilForever commented on Includes/CubbyTower/Components/Cooldown.hpp
> +//! This struct stores the data for cooldowns for attack cooldowns or ability cooldowns
```suggestion
//! This struct stores the data for cooldowns for attack cooldowns or ability cooldowns.
```

2022-02-21 15:11 UTC, utilForever commented on Includes/CubbyTower/Components/Cooldown.hpp
> +//! \brief Cooldown Struct.
```suggestion
//! \brief Cooldown struct.
```

2022-02-21 15:11 UTC, utilForever commented on Includes/CubbyTower/Helpers/ProjectileHelpers.hpp
> +//! Makes Projectile Heading from \p tower to \enemy that follows tower's aspects
```suggestion
//! Makes a projectile Heading from \p tower to \enemy that follows tower's aspects
```

2022-02-21 15:11 UTC, utilForever commented on Includes/CubbyTower/Helpers/ProjectileHelpers.hpp
> +//! \param tower The tower entity.
```suggestion
//! \param tower A tower entity.
```

2022-02-21 15:11 UTC, utilForever commented on Includes/CubbyTower/Systems/AttackSystem.hpp
> +//! \param deltaTime Time passed from last Attack Update
```suggestion
//! \param deltaTime The time passed from last attack is updated.
```

2022-02-21 15:11 UTC, utilForever commented on Sources/CubbyTower/Game.cpp
> +#include <CubbyTower/Systems/AttackSystem.hpp>
You should apply `clang-format`.

2022-02-21 15:11 UTC, utilForever commented on Sources/CubbyTower/Game.cpp
> +    UpdateAttackSystem(registry, deltaTime);
I think this function should be in `Simulate()`.

2022-02-21 15:11 UTC, utilForever commented on Sources/CubbyTower/Helpers/ProjectileHelpers.cpp
> +namespace CubbyTower
```suggestion
#include <CubbyTower/Components/Velocity.hpp>

#include <cmath>

namespace CubbyTower
```

2022-02-21 15:11 UTC, utilForever commented on Sources/CubbyTower/Helpers/ProjectileHelpers.cpp
> +    float speed = 1.0; //TODO : add projectile speed component in tower
```suggestion
    float speed = 1.0f; // TODO: Add projectile speed component in tower
```

2022-02-21 15:11 UTC, utilForever commented on Sources/CubbyTower/Helpers/ProjectileHelpers.cpp
> +    // TODO : add lifetime by attackrange / speed
```suggestion
    // TODO: Add lifetime by attack range / speed
```

2022-02-21 15:11 UTC, utilForever commented on Sources/CubbyTower/Helpers/ProjectileHelpers.cpp
> +    registry.emplace<Size>(entity, 1.0f, 1.0f); // TODO : add projectile size in tower
```suggestion
    registry.emplace<Size>(entity, 1.0f, 1.0f); // TODO: Add projectile size in tower
```

2022-02-21 15:11 UTC, utilForever commented on Sources/CubbyTower/Helpers/ProjectileHelpers.cpp
> +    }
```suggestion
    const Position positionDiff = { enemyPosition.x - towerPosition.x, enemyPosition.y - towerPosition.y };
    const float distance = std::sqrt(positionDiff.x * positionDiff.x + positionDiff.y * positionDiff.y);
    if (distance == 0.0f) {
        registry.emplace<Velocity>(entity, 0.0f, 0.0f);
        return;
    }
```

2022-02-21 15:11 UTC, utilForever commented on Sources/CubbyTower/Helpers/ProjectileHelpers.cpp
> +    registry.emplace<Velocity>(entity, speed * positionDiff.x / distance , speed * positionDiff.y / distance );
```suggestion
    registry.emplace<Velocity>(entity, speed * positionDiff.x / distance, speed * positionDiff.y / distance);
```

2022-02-21 15:11 UTC, utilForever commented on Sources/CubbyTower/Systems/AttackSystem.cpp
>          for (auto enemy : registry.view<Tag::Enemy>())
```suggestion
        // TODO: Add cooldown check

        for (auto enemy : registry.view<Tag::Enemy>())
```

2022-02-21 15:11 UTC, utilForever commented on Tests/UnitTests/Systems/AttackSystemTests.cpp
> +#include <CubbyTower/Components/Velocity.hpp>
You should apply `clang-format`.

2022-02-21 15:11 UTC, utilForever commented on Tests/UnitTests/Systems/AttackSystemTests.cpp
> +    UpdateAttackSystem(registry, 0.0);
```suggestion
    UpdateAttackSystem(registry, 0.0f);
```

2022-02-21 15:11 UTC, utilForever commented on Tests/UnitTests/Systems/AttackSystemTests.cpp
> +        CHECK_EQ(vel.vy, 1.0);
```suggestion
        CHECK_EQ(vel.dx, 0.0f);
        CHECK_EQ(vel.dy, 1.0f);
```

2022-02-21 15:38 UTC, IHIHHIHI commented on Includes/CubbyTower/Components/Velocity.hpp
> +    float vy;
이건 의미상 dx / dt 나타내는 것이라 vx가 맞지 않나요??

2022-02-21 15:38 UTC, IHIHHIHI commented on Sources/CubbyTower/Game.cpp
> +    UpdateAttackSystem(registry, deltaTime);
이건 그 PR 보기 전에 작업한 부분이라 그렇네요. 수정하겠습니다

2022-02-21 15:43 UTC, IHIHHIHI commented on Tests/UnitTests/Systems/AttackSystemTests.cpp
> +#include <CubbyTower/Components/Velocity.hpp>
이건 왜 적용이 안됐을까요...ㅜ

2022-02-21 15:49 UTC, utilForever commented on Includes/CubbyTower/Components/Velocity.hpp
> +    float vy;
`Position` 컴포넌트가 `x`랑 `y`를 쓰니 속력은 `dx`와 `dy`를 쓰는게 문맥상 맞지 않을까 싶은데 ㅇㅅㅇ;

2022-02-21 15:49 UTC, IHIHHIHI commented on Tests/UnitTests/Systems/AttackSystemTests.cpp
> +#include <CubbyTower/Components/Velocity.hpp>
format 설정 다해두고 save시 적용을 안켜두었습니다. 이제 켜놓았고 지금 파일들은 다시 포맷해서 올릴게용

2022-02-21 15:53 UTC, IHIHHIHI commented on Includes/CubbyTower/Components/Velocity.hpp
> +    float vy;
Position에 x + vx * deltatime이 들어가니까 vx가 맞지 않나요??

2022-02-21 15:54 UTC, utilForever commented on Includes/CubbyTower/Components/Velocity.hpp
> +    float vy;
컴포넌트 이름이 `Velocity`인데 멤버 변수에 `v`가 들어가는 건 의미가 겹친다고 생각합니다.

2022-02-21 16:06 UTC, utilForever commented on Includes/CubbyTower/Components/Velocity.hpp
> +    float vy;
논의를 통해 `x`, `y`로 바꾸기로 합의했습니다.

2022-02-22 17:17 UTC, utilForever approved these changes
LGTM now. Thanks for your hard work! 🎉

2022-02-22 17:17 UTC, merged