Monster
utilForever/CubbyTower pull request #54
Opened 2022-11-09 07:32 UTC by red1108

2022-11-09 08:04 UTC, IHIHHIHI commented
PR 설명을 써주세요..!

2022-11-13 10:57 UTC, IHIHHIHI approved these changes
LGTM!

2022-11-13 10:58 UTC, IHIHHIHI commented
한가지 아이디어가 있다면, 앞으로도 죽음의 메아리(?) 효과가 꽤 있을 것 같은데 이러한 것을 함수 component로 체계적으로 다는 방식이 있으면 좋을 것 같아요

2022-11-15 06:59 UTC, red1108 commented
전부터 든 생각인데, 타워를 만들때 함수 인자로 추가적으로 넘길 수 있게 했으면 좋을것 같습니다
balloonLV1, balloonLV2, balloonLV3 이런식으로 말고 함수 인자로 level을 넣는 방식으로 하고 싶은데 코드를 어떻게 고쳐야 할지 모르겠습니다

2022-11-19 12:50 UTC, utilForever commented
> 전부터 든 생각인데, 타워를 만들때 함수 인자로 추가적으로 넘길 수 있게 했으면 좋을것 같습니다 balloonLV1, balloonLV2, balloonLV3 이런식으로 말고 함수 인자로 level을 넣는 방식으로 하고 싶은데 코드를 어떻게 고쳐야 할지 모르겠습니다

원하면 만들 수 있는데, level 뿐만 아니라 체력이나 이동 속도 같은 정보들도 같이 있을텐데 구조체로 하나 따로 만들길 원하는 건가?

2022-11-19 13:00 UTC, utilForever requested changes
수정할 부분들이 있어서 리뷰 남겨놨어. 확인 부탁해!

2022-11-19 13:00 UTC, utilForever commented on Includes/CubbyTower/Components/Position.hpp
> +
여기는 무엇이 바뀐 건지...?

2022-11-19 13:00 UTC, utilForever commented on Sources/CubbyTower/Systems/DeathTimerSystem.cpp
> +#include <CubbyTower/Components/Name.hpp>
헤더 파일을 추가한 이유가 있을까?

2022-11-19 13:00 UTC, utilForever commented on Sources/CubbyTower/Helpers/ShootingHelpers.cpp
> +#include <iostream>
이 헤더 파일이 필요한 이유가 있을까?

2022-11-19 13:00 UTC, utilForever commented on Sources/CubbyTower/Helpers/ShootingHelpers.cpp
> +    if (name.name == "MOAB")
이름으로 비교하는 것도 좋지만, 풍선의 종류를 열거체로 만들어서 구별하는게 좀 더 좋을 거 같아.

2022-11-19 13:00 UTC, utilForever commented on Includes/CubbyTower/Helpers/MonsterHelpers.hpp
> +//! position The position to place a normal balloon.
여기 주석 망가졌네. \param이 새 라인으로 가도록 수정해야돼.

2022-11-19 13:00 UTC, utilForever commented on Includes/CubbyTower/Helpers/MonsterHelpers.hpp
> +//! Creates a Massive Ornary Air Blimp (MOAB) balloon.
빈 줄 추가.

```suggestion
void CreatePigeonBalloon(entt::registry& registry, const Position& position);

//! Creates a Massive Ornary Air Blimp (MOAB) balloon.
```

2022-11-19 13:00 UTC, utilForever commented on Sources/CubbyTower/Helpers/MonsterHelpers.cpp
> +constexpr static int NORMAL_BALLON_HEALTH[] = { 30, 90, 160 };
이렇게 해도 되겠지만, 구조체로 만들어서 전달하는 방식이 좀 더 좋아보여.

2022-11-19 13:00 UTC, utilForever commented on Sources/CubbyTower/Helpers/MonsterHelpers.cpp
> +constexpr static int NORMAL_BALLON_HEALTH[] = { 30, 90, 160 };
그리고 오타가 있네. `BALLON`이 아니라 `BALLOON`.

2022-11-19 13:42 UTC, red1108 commented on Sources/CubbyTower/Helpers/ShootingHelpers.cpp
> +#include <iostream>
디버깅할때 해놓고 안지웠네요 ㅜㅜ

2022-12-02 08:35 UTC, utilForever reviewed
Can you change the name of struct?

2022-12-02 08:35 UTC, utilForever commented on Sources/CubbyTower/Helpers/MonsterHelpers.cpp
> +struct Balloon_info
```suggestion
struct BalloonInfo
```

2022-12-03 13:54 UTC, utilForever approved these changes
LGTM now. Thanks for your work! 🐲

2022-12-03 13:58 UTC, merged